######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 13 12:45:30 2011
######################################################################

TEMPLATE = app
QT += core testlib
TARGET = test
DEPENDPATH += . geometry
INCLUDEPATH += . geometry ../common
LIBS += -L../common -lcommon -lGLEW

# Input
HEADERS += geometry/testbox.h \
    geometry/testarrays.h
SOURCES += geometry/testbox.cpp \
    main.cpp \
    geometry/testarrays.cpp
