######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 13 12:42:21 2011
######################################################################

TEMPLATE = lib
CONFIG += staticlib
TARGET = common
DEPENDPATH += . geometry
INCLUDEPATH += . geometry

# Input
HEADERS += geometry/box.h
SOURCES += geometry/box.cpp
